# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Sara Kodeiri
tagline:          ''
description:      'A computer engineering undergraduate student at <a href="https://iust.ac.ir/" target="_blank">IUST</a>.'
url:              
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
